name: CI and Create Pull Request

on:
  push:
    branches:
      - feature/*

env:
  ENVIRONMENT_NAME: DEV

jobs:
  build:
    runs-on: ubuntu-latest
    name: CI
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test

  create_pull_request:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        run: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed -e "s/refs\/heads\///")
          PR_TITLE="Feature Branch Pull Request"
          PR_BODY="This pull request was automatically created from the feature branch."
          PR_BASE="develop"
          PR_LABELS="enhancement, ${{ env.ENVIRONMENT_NAME }}"

          gh pr create --title "$PR_TITLE" --body "$PR_BODY" --base "$PR_BASE" --label "$PR_LABELS" --repo ${{ github.repository }} --head "${{ github.repository }}:$BRANCH_NAME"
