name: CI and Create Pull Request

on:
  push:
    branches:
      - feature/*

env:
  ENVIRONMENT_NAME: DEV

jobs:
  build:
    runs-on: ubuntu-latest
    name: CI
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Change directory to miniapi
        run: cd ./MiniApi && ls -la

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"

      - name: Restore dependencies
        run: dotnet restore MiniApi.sln

      - name: Build project
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --configuration Release --no-restore
